### ISSUE TITLE
Using MySQL and Micronaut Data

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-guides#690]
- [x] [Using MySQL and Micronaut Data with Oracle Cloud](https://github.com/micronaut-projects/micronaut-guides/issues/691)
- [ ] [Using MySQL and Micronatu Data with Azure](https://github.com/micronaut-projects/micronaut-guides/issues/692)
- [x] [Using MySQL and Micronaut Data with GCP](https://github.com/micronaut-projects/micronaut-guides/issues/693)
- [x] [Using MySQL and Micronaut Data with AWS](https://github.com/micronaut-projects/micronaut-guides/issues/694)

**Comment by sdelamo** [comment]
I assume the idea is to:

Teuse the [Access a Database with Micronaut Data JDBC](https://guides.micronaut.io/latest/micronaut-data-jdbc-repository-gradle-java.html) and move every shared copy to common snippets.

Each guide contain individual cloud settings with screenshots explaining the users how to set up a Relational database and how to configure the JDBC Url etc.

**Comment by sdelamo** [comment]
it would be good to have a guide explaining Cloud Run + Cloud SQL in GCP which plays well.
