### ISSUE TITLE
Retrieving Secrets

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-guides#703]
- [ ] [Retrieving Secrets with AWS Secrets Manager](https://github.com/micronaut-projects/micronaut-guides/issues/702)
- [ ] [Retrieving Secrets with Azure Key Vault](https://github.com/micronaut-projects/micronaut-guides/issues/700)
- [x] [Retrieving Secrets with Oracle Cloud Vault](https://github.com/micronaut-projects/micronaut-guides/issues/699)

**Comment by sdelamo** [comment]
Please, note that we already have an AWS Secrets Manager guide: 

https://guides.micronaut.io/latest/micronaut-aws-secretsmanager.html

It would be good to based other guides in the same code base and example.

Of course, improve the AWS Secrets Manager guide as well if anything is lacking or difficult to understand.

**Comment by sdelamo** [comment]
I wrote a guide for Secrets rotation as well which is interesting if you use a secrets manager solution: https://guides.micronaut.io/latest/micronaut-aws-secretsmanager-rotation.html

**Comment by sdelamo** [comment]
It would be interesting to write an integratino with [1Password Secrets Automation](https://1password.com/secrets/) and also a guide with [HashiCorp Vault](https://www.vaultproject.io)

**Comment by agent-reed** [comment]
May I volunteer to re-write the guide for AWS secrets management? I've tried to follow that guide and found it almost impossible to follow.

**Comment by sdelamo** [comment]
@agent-reed please send a PR with your suggestions

**Comment by ojebari-ma** [comment]
Can you please confirm that this is still an issue in the latest version of Micronaut?
