### ISSUE TITLE
Application Monitoring

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-guides#708]
- [ ] [Application Monitoring on OCI](https://github.com/micronaut-projects/micronaut-guides/issues/704)
- [ ] [Application Monitoring on Azure](https://github.com/micronaut-projects/micronaut-guides/issues/705)
- [ ] [Application Monitoring on GCP](https://github.com/micronaut-projects/micronaut-guides/issues/706)
- [ ] [Application Monitoring on AWS](https://github.com/micronaut-projects/micronaut-guides/issues/707)

**Comment by ojebari-ma** [comment]
Can you please confirm that this is still an issue in the latest version of Micronaut?
