### ISSUE TITLE
Application Tracing

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-guides#713]
- [ ] [Application Tracining on OCI](https://github.com/micronaut-projects/micronaut-guides/issues/709)
- [ ] [Application Tracining on Azure](https://github.com/micronaut-projects/micronaut-guides/issues/710)
- [ ] [Application Tracining on GCP](https://github.com/micronaut-projects/micronaut-guides/issues/711)
- [ ] [Application Tracining on AWS](https://github.com/micronaut-projects/micronaut-guides/issues/712)

**Comment by sdelamo** [comment]
I would like this guides to be based on the currently existing tracing guides
https://guides.micronaut.io/latest/micronaut-microservices-distributed-tracing-jaeger.html

**Comment by ojebari-ma** [comment]
Can you please confirm that this is still an issue in the latest version of Micronaut?
